default:
  directories:
    dir_scenario: "/Users/jkastl/Desktop/p4s_projects/test_project_p4b/scenario"
    dir_abcd: "/Users/jkastl/Desktop/p4s_projects/test_project_p4b/abcd"
    dir_raw: "/Users/jkastl/Desktop/p4s_projects/test_project_p4b/raw"
    dir_matched: "/Users/jkastl/Desktop/p4s_projects/test_project_p4b/matched"
    dir_output: "/Users/jkastl/Desktop/p4s_projects/test_project_p4b/output"
  file_names:
    filename_raw: "gr1_sample_loanbook_100_121.csv"
    filename_scenario_tms: "scenarios_2022_p4b.csv"
    filename_scenario_sda: "scenarios_2022_ei_p4b.csv"
    filename_abcd: "2023-02-17_AI_RMI_PACTA for Banks Free dataset_EO_2022Q4.csv"
  project_parameters:
    scenario_source: "weo_2022"
    scenario_select: "nze_2050"
    region_select: "global"
    # normally the start year should correspond with year of the publication of
    # the scenario in use
    start_year_select: 2022
    time_frame_select: 5
    # regions must be available for the selected scenario
    benchmark_regions_select: "global,european union"
    remove_inactive_companies: TRUE
  sector_split:
    apply_sector_split: TRUE
    sector_split_type: "equal_weights"
    # sector_split_type: "worst_case"
    dir_split_company_id: "PATH/TO/SPLIT/FOLDER"
    filename_split_company_id: "split_company_ids.csv"
    dir_advanced_company_indicators: "PATH/TO/ADVANCED_COMP_INDICATORS/FOLDER"
    filename_advanced_company_indicators: "advanced_company_indicators.xlsx"
  matching:
    prep_input_level: "direct_loantaker"
    params_match_name:
      by_sector: TRUE
      min_score: 0.9
      method: "jw"
      p: 0.1
      overwrite: NULL
      join_id: NULL
    own_sector_classification:
      use_own_sector_classification: FALSE
      dir_own_sector_classification: "PATH/TO/SECTOR_CLASSIFICATION/FOLDER"
      filename_own_sector_classification: "own_sector_classification.csv"



