default:
  directories:
    dir_input: "path/to/input_folder"
    dir_prepared_abcd: "path/to/prepared_abcd"
    dir_matched_loanbooks: "path/to/matched_loanbooks"
    dir_prioritized_loanbooks_and_diagnostics: "path/to/prioritized_loanbooks_and_diagnostics"
    dir_analysis: "path/to/analysis"
  file_names:
    filename_scenario_tms: "scenarios_2022_tms.csv"
    filename_scenario_sda: "scenarios_2022_sda.csv"
    filename_abcd: "abcd.xlsx"
    sheet_abcd: "Company Indicators - PACTA Comp"
  project_parameters:
    scenario_source: "weo_2022"
    scenario_select: "nze_2050"
    region_select: "global"
    # normally the start year should correspond with year of the publication of
    # the scenario in use
    start_year: 2022
    time_frame: 5
    by_group: "group_id"
  sector_split:
    apply_sector_split: TRUE
    sector_split_type: "equal_weights"
    filename_split_company_id: "split_company_ids.csv"
    filename_advanced_company_indicators: "advanced_company_indicators.xlsx"
    sheet_advanced_company_indicators: "Company Activities"
  matching:
    params_match_name:
      by_sector: TRUE
      min_score: 0.9
      method: "jw"
      p: 0.1
      overwrite: NULL
      join_id: NULL
    manual_sector_classification:
      use_manual_sector_classification: FALSE
      filename_manual_sector_classification: "manual_sector_classification.csv"
  match_prioritize:
    priority: NULL
  prepare_abcd:
    remove_inactive_companies: TRUE
  match_success_rate:
    plot_width: 12
    plot_height: 8
    plot_units: "in"
    plot_resolution: 300
